services:
  amazon-q:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${AMAZON_Q_WORKSPACE:-${AMAZON_Q_DEFAULT_WORKSPACE:-$HOME}}:/home/developer/workspace:cached
      - ~/.aws/nskp_config/netskope-cert-bundle.pem:/home/developer/.aws/nskp_config/netskope-cert-bundle.pem:cached
      - ./.amazonq:/home/developer/workspace/.amazonq:cached
      - ./.vscode:/vscode:cached
    env_file:
      - ./.env
    command: sleep infinity
    user: developer
    healthcheck:
      test: ["CMD", "sh", "-c", "q --version > /dev/null 2>&1 && /usr/local/scripts/build-complete.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
